# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.29595175 0.57253736 0.78409712 ... 0.86720742 0.27618593 0.68819282]
 [0.79807641 0.22845519 0.87526491 ... 0.48310917 0.6233597  0.80524101]
 [0.23166877 0.39194196 0.36537368 ... 0.84489467 0.65110193 0.91173743]
 ...
 [0.73432958 0.73656892 0.35937873 ... 0.76093049 0.43819804 0.24406306]
 [0.02093862 0.19427046 0.56853783 ... 0.33266843 0.03271906 0.10609426]
 [0.70412993 0.13353871 0.32230315 ... 0.72460548 0.21066046 0.71973626]]
[[0.71367814 0.32941999 0.37426564 ... 0.9762934  0.42178526 0.59622676]
 [0.76139087 0.14806844 0.51246148 ... 0.56028367 0.84691403 0.45734754]
 [0.58764027 0.55444295 0.08685329 ... 0.78175822 0.78318138 0.41595858]
 ...
 [0.19027543 0.50612104 0.09542015 ... 0.64067013 0.87346806 0.60240549]
 [0.73392988 0.58800123 0.0762459  ... 0.19129045 0.90172403 0.53608461]
 [0.31864833 0.56972661 0.97680916 ... 0.13732139 0.05816169 0.04966427]]


Без использования numpy

In [42]:
def mult(a, b):
  a_size = len(a)
  result = [[0] * a_size for _ in range(a_size)]

  for i in range(a_size):
    for j in range(a_size):
      for k in range(a_size):
        result[i][j] += a[i][k] * b[k][j]

  print(result)
  return result

C использованием numpy

In [44]:
def np_mult(a, b):
    result = np.dot(a, b)
    print(result)
    return result

In [43]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

[[21.884204897609965, 23.238003814719494, 24.375123188188628, 23.969606982185695, 23.08651124447591, 22.4337191600716, 23.814899739348206, 25.865225362947452, 23.8276020473981, 22.20540703490182, 26.0545321217335, 26.73289462440003, 23.83474836848183, 21.814731310701564, 21.633863955820694, 23.32234420878676, 23.007938276411615, 24.76322176515022, 26.84142323982022, 24.785409996013726, 22.31685970930191, 26.375985117943255, 25.954822843318038, 23.6630753235311, 24.302027119172806, 24.90993945179095, 23.313320918238237, 22.995703144626813, 22.544168833525184, 20.161878685437706, 24.55847230080019, 23.479775111339563, 23.805406869848444, 24.219763298746145, 24.247921628964033, 22.92749438382377, 23.21834230467174, 24.912466661885738, 26.20948435494825, 22.818790831644453, 26.759300733216534, 24.95723866323069, 24.391500487942434, 23.241491493432843, 25.06987646042035, 21.48759609982971, 23.06426403465577, 24.34127985241061, 23.008149166764543, 23.150112287296498, 23.551864286647014, 23.9

In [45]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

[[21.8842049  23.23800381 24.37512319 ... 20.77345004 26.08784078
  25.03707785]
 [23.20479917 22.99866028 24.80517796 ... 21.41634745 24.68921132
  24.91987941]
 [26.60412028 27.06510839 28.68599452 ... 25.2123494  28.80614459
  27.78248556]
 ...
 [23.42224732 21.67427438 21.30907508 ... 20.23505492 24.18909619
  24.4839647 ]
 [23.1497313  24.90679172 23.88722169 ... 20.78205798 26.95772558
  25.25183441]
 [25.14793204 25.10755614 27.21376291 ... 23.34254158 28.82624893
  26.93910297]]
CPU times: user 3.22 ms, sys: 4.17 ms, total: 7.39 ms
Wall time: 4.74 ms


In [46]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5084822280186927e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [47]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.49724367 0.12427411 0.9392451 ] [0.22119812 0.70993816 0.62338363]


In [49]:
def scalar_product(a,b):
    s = 0
    len_a = (sum([x**2 for x in a]))**0.5
    len_b = (sum([x**2 for x in b]))**0.5
    scalar = sum([a[i]*b[i] for i in range(len(a))])
    cos_a = scalar / (len_a * len_b)
    s = len_a * len_b * cos_a
    return s

In [48]:
def np_scalar_product(a,b):
    s = 0
    s = np.vdot(a, b)
    return s

In [51]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 51 µs, sys: 0 ns, total: 51 µs
Wall time: 55.8 µs
CPU times: user 45 µs, sys: 0 ns, total: 45 µs
Wall time: 48.2 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** NumPy предлагает реализацию многих алгоритмов и функций на C, что способствует его высокой производительности.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [99]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = 0
  for i in range(len(a)):
    if a[i][i] % 2 == 0:
      res += a[i][i]
    if a[i][len(a) - i - 1] % 2 == 0:
      res += a[i][len(a) - i - 1]

  if len(a)%2 != 0:
    if a[int(len(a)/2)][int(len(a)/2)] % 2 == 0:
      res -= a[int(len(a)/2)][int(len(a)/2)]
  return res

In [97]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 6, 9, 1, 7],
       [5, 1, 3, 3, 6],
       [1, 6, 8, 7, 6],
       [9, 6, 2, 1, 9],
       [3, 2, 2, 2, 5]])

In [177]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 49 µs, sys: 0 ns, total: 49 µs
Wall time: 53.2 µs


22

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [110]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = [[0, 0] for i in range(len(*A))]
    for i in range(len(A)):
      result[i][0] = A[i]
      result[i][1] = np.cumsum(result, axis=0) / (i+1)
    return result

In [113]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[9.03084821e-01 4.10480886e-01 6.24234142e-01 7.14918699e-01
 8.16602414e-01 4.15949850e-01 9.94892711e-03 5.63512564e-01
 3.16422679e-01 3.30525363e-01 5.30795416e-02 8.68788203e-01
 9.88701551e-01 1.08131826e-01 7.48612316e-01 9.08803624e-02
 9.02606328e-01 7.69401646e-01 9.52427606e-01 5.89055879e-01
 8.18872648e-01 3.14199888e-01 8.28595335e-01 6.96930764e-01
 3.36297865e-01 7.14201868e-01 1.03535835e-01 2.98216778e-01
 4.44031759e-01 5.46037703e-01 4.28642265e-01 8.19085663e-01
 5.80509392e-01 5.27336493e-01 9.03947383e-01 9.36632011e-01
 5.93058198e-01 9.08782933e-01 2.13572441e-01 3.97686356e-01
 9.69060958e-01 4.67781135e-01 8.66864602e-01 7.32241959e-02
 6.11468122e-01 8.30308756e-01 7.84507148e-01 9.65059254e-01
 9.12335311e-02 6.38979001e-01 3.51444498e-01 5.35761875e-01
 2.04758715e-01 9.28513573e-01 4.46027580e-01 9.38798355e-01
 2.28010343e-01 5.17927671e-01 9.91408559e-01 4.27335398e-01
 1.21800491e-01 8.65585041e-01 7.49948293e-01 9.55376225e-01
 7.45485671e-01 5.663563

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [127]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = [[], []]
    start = 0
    start_item = 0
    for i in range(len(a)):
      if i == 0:
        start_item = a[i]
      if start_item != a[i] or i == len(a) - 1:
        result[0].append(start_item)
        result[1].append(np.count_nonzero((a[start:i+1] == start_item)))
        start = i
        start_item = a[i]

    return result

In [132]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(x)
print(num)

CPU times: user 81 µs, sys: 0 ns, total: 81 µs
Wall time: 86.1 µs
[1, 2, 3, 1, 5, 2, 3]
[1, 2, 2, 2, 2, 1, 2]


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [175]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = None
    changed_array = np.array([0 for i in range(len(X))])
    for i in range(len(X)):
      if i % 2 == 0:
        changed_array[i] = X[i]**3
      else:
        changed_array[i] = a
    result = np.hstack((X, changed_array))
    print(result)
    return result

In [176]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

[  1   3   5   7   9   1   5 125   5 729]
CPU times: user 850 µs, sys: 0 ns, total: 850 µs
Wall time: 800 µs
